### get api list
http://localhost:6000/

### get blocks
http://localhost:6000/blocks


### add block
POST http://localhost:6000/blocks
{
    "message": "Data for my block"
}

### get block
http://localhost:6000/blocks/0c726b371601262a085b403c2d1fa6676cd4c9d3c99b97cd5e5bb7ae1980fb53